api/urls.py
from django.urls import include, re_path
from rest_framework import routers

from api.views import (APICategoryViewSet, APIPostViewSet, APIProfileViewSet,
                       APISubCategoryViewSet, APITagViewSet, NewsLetterView,
                       UserViewSet)
from blog.models import Post

router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'tags', APITagViewSet)
router.register(r'posts', APIPostViewSet)
router.register(r'categories', APICategoryViewSet)
router.register(r'subcategories', APISubCategoryViewSet)
router.register(r'profile', APIProfileViewSet)



urlpatterns = [
    re_path(r'^', include(router.urls)),
    re_path(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    re_path(r'^newsletter/',NewsLetterView.as_view(), name = "subscribe"),

    # re_path(r'^posts/',APIPostListCreateView.as_view(), name = "list"),
    # re_path(r'^post/(?P<pk>[0-9a-f]{8}-[0-9a-f]{4}-[0-5][0-9a-f]{3}-[089ab][0-9a-f]{3}-[0-9a-f]{12})/$', APIPostDetailView.as_view(), name = 'detail'),
    # re_path(r'^post/(?P<pk>[0-9a-f]{8}-[0-9a-f]{4}-[0-5][0-9a-f]{3}-[089ab][0-9a-f]{3}-[0-9a-f]{12})/edit/$', APIPostUpdateDestroyDetailView.as_view(), name = 'edit'),
    # re_path(r'^tags/', APITagListCreateView.as_view(), name = 'list'),
    # re_path(r'^tag/(?P<pk>[-\d]+)/', APITagDetailView.as_view(), name = 'detail'),
    # re_path(r'^tag/(?P<pk>[-\d]+)/edit/$', APITagEditView.as_view(), name = 'edit'),
    
]

category/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path

from . import views

app_name = 'category'

urlpatterns = [
    re_path(r'^list/', views.CategoryListView.as_view(), name = 'cat-list'), 
    re_path(r'^create/', views.CreateCategoryView.as_view(), name = 'cat-create'), 
    re_path(r'^(?P<pk>[-\d]+)/delete/', views.DeleteCategoryView.as_view(), name = 'cat-delete'),
    re_path(r'^(?P<pk>[-\d]+)/edit/', views.CategoryUpdateView.as_view(), name='cat-update'),
    re_path(r'^(?P<slug>[-\w]+)/', views.posts_list_by_category, name='posts_list_by_category'),

]
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)+static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

dashboard/urls.py
from django.contrib.sitemaps.views import sitemap
from django.urls import re_path

from dashboard.sitemaps import PostSitemap, StaticViewSitemap

from . import views

sitemaps = {
    'static': StaticViewSitemap,
    'post':PostSitemap
}

app_name = 'dashboard'

urlpatterns = [
    re_path(r'home/',views.DashboardView.as_view(), name = 'home'), 
    re_path(r'^password/$', 
        views.ChangePasswordView.as_view(),name='password_change'),
    
    re_path(r'^list-post/$', views.PostListView.as_view(), name = 'post-list'), 
    re_path(r'^create-post/$', views.PostCreateView.as_view(), name = 'post-create'), 
    re_path(r'^(?P<pk>[0-9a-f]{8}-[0-9a-f]{4}-[0-5][0-9a-f]{3}-[089ab][0-9a-f]{3}-[0-9a-f]{12})/delete-post/$', views.PostDeleteView.as_view(), name = 'post-delete'),
    re_path(r'^(?P<pk>[0-9a-f]{8}-[0-9a-f]{4}-[0-5][0-9a-f]{3}-[089ab][0-9a-f]{3}-[0-9a-f]{12})/edit-post/$', views.PostUpdateView.as_view(), name='post-update'),
    re_path(r'^list-news/$', views.NewListView.as_view(), name = 'new-list'), 
    re_path(r'^create-news/$', views.NewCreateView.as_view(), name = 'new-create'), 
    re_path(r'^(?P<pk>[0-9a-f]{8}-[0-9a-f]{4}-[0-5][0-9a-f]{3}-[089ab][0-9a-f]{3}-[0-9a-f]{12})/delete-new/$', views.NewDeleteView.as_view(), name = 'new-delete'),
    re_path(r'^(?P<pk>[0-9a-f]{8}-[0-9a-f]{4}-[0-5][0-9a-f]{3}-[089ab][0-9a-f]{3}-[0-9a-f]{12})/edit-new/$', views.NewUpdateView.as_view(), name='new-update'),
    re_path(r'^sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),

]

insurance/urls.py

from dj_rest_auth.registration.views import ConfirmEmailView, VerifyEmailView
from dj_rest_auth.views import PasswordResetConfirmView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path, re_path

from insurance import views

urlpatterns = [
    re_path(r'^i18n/', include('django.conf.urls.i18n')),
    re_path(r'^', include('accounts.urls',namespace='accounts')),
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^', include('blog.urls')),
    re_path(r'^new/', include('news.urls')),
    re_path(r'^search/', include('search.urls')),
    re_path(r'^dashboard/', include('dashboard.urls')),
    re_path(r'^tag/', include('tag.urls')),
    re_path(r'^about/', include('aboutus.urls' ,namespace='about_us')),
    re_path(r'^settings/', include('aboutus.urls')),
    re_path(r'^team/', include('team.urls')),
    re_path(r'^category/', include('category.urls')),
    re_path(r'^contact/', include('contact.urls')),
    re_path(r'^faq/', include('faq.urls')),
    re_path(r'^customer-feedback/', include('feedback.urls')),
    re_path(r'^user/', include('users.urls')),
    re_path(r'^frontend/', include('renewal.urls')),
    re_path(r'^ticket/', include('tickets.urls')),
    re_path(r'^social-auth/', include('social_django.urls', namespace='social')),
    re_path(r'^ratings/', include('star_ratings.urls', namespace='ratings')),
    re_path(r'^', include('django.contrib.auth.urls')),
    re_path(r'^__debug__/', include('debug_toolbar.urls')),
    re_path(r'^accounts/login/$', auth_views.LoginView.as_view(template_name='frontend/accounts/login.html'), name='login'),
    re_path(r'^accounts/logout/$', auth_views.LogoutView.as_view(), name='logout'),
    re_path(r'^accounts/reset/$',
        auth_views.PasswordResetView.as_view(
            template_name='frontend/accounts/password_reset.html',
            html_email_template_name='frontend/accounts/password_reset_email.html',
            email_template_name='frontend/accounts/password_reset_email.html',
            subject_template_name='frontend/accounts/password_reset_subject.txt'
        ),
        name='password_reset'),
    re_path(r'^accounts/reset/done/$',
        auth_views.PasswordResetDoneView.as_view(template_name='frontend/accounts/password_reset_done.html'),
        name='password_reset_done'),
    re_path(r'^accounts/reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        auth_views.PasswordResetConfirmView.as_view(template_name='frontend/accounts/password_reset_confirm.html'),
        name='password_reset_confirm'),
    re_path(r'^accounts/reset/complete/$',
        auth_views.PasswordResetCompleteView.as_view(template_name='frontend/accounts/password_reset_complete.html'),
        name='password_reset_complete'),
    re_path(r'^settings/password/done/$',
        auth_views.PasswordChangeDoneView.as_view(template_name='frontend/accounts/password_change_done.html'),
        name='password_change_done'),
    re_path(r'^.*\.*', views.pages, name='pages'),   

    #######################
        ### DRF ###
    ####################### 
    # re_path(r'^api/', include('api.urls')),
    # re_path(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    # re_path(r'^api/v1/rest-auth/', include('dj_rest_auth.urls')),
    # re_path(r'^api/v1/rest-auth/registration/', include('dj_rest_auth.registration.urls')),
    # re_path(r'^api/v1/rest-auth/account-confirm-email/(?P<key>[-:\w]+)/$',  ConfirmEmailView.as_view(), name='account_confirm_email'),
    # re_path(r'^api/v1/rest-auth/account-confirm-email/', VerifyEmailView.as_view(), name='account_email_verification_sent'),
    # re_path(r'^api/v1/rest-auth/password/reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_URL)


category/models.py
from tabnanny import verbose

from ckeditor.fields import RichTextField
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from painless.models.mixins import OrganizedMixin
from painless.models.validations import (validate_file_extension,
                                         validate_file_size)


class Category(OrganizedMixin):
    icon = models.CharField(_("ایکن"), max_length=128, blank = True, null = True)
    parent = models.ForeignKey('self', default=None, null=True, blank=True, on_delete=models.SET_NULL,
                               related_name='subcategory', verbose_name="زیر مجموعه")
    banner=models.ImageField(_('تصویر'),
        upload_to='category/%Y/%m/%d', blank=True, validators=[validate_file_extension, validate_file_size])
    content = RichTextField(_('پیام'),blank=True,null=True)

    class Meta:
        ordering = ['-created']
        verbose_name = 'دسته بندی'
        verbose_name_plural = 'دسته بندیها'
    
    def __str__(self):
        return self.title

    def children(self):
        return Category.objects.filter(parent=self)


    @property
    def is_parent(self):
        """Return `True` if instance is a parent."""
        if self.parent is not None:
            return False
        return True

    def get_absolute_url(self):
        return reverse('blog:detail_by_category_slug', kwargs={"slug": self.slug})


    def posts_base_on_category(self):
        return reverse('category:posts_list_by_category', kwargs={"slug": self.slug})
    

dashboard/models.py
from django.db import models

# Create your models here.

category/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

from category.models import Category


class CategoryForm(forms.ModelForm):
    content = forms.CharField(label='پیام', widget=forms.Textarea(attrs={'class': 'ckeditor'}))
    class Meta:
        model = Category
        exclude = ("slug","published_at")


category/views.py


from django.contrib import messages
from django.contrib.auth.mixins import (LoginRequiredMixin,
                                        PermissionRequiredMixin)
from django.contrib.messages.views import SuccessMessageMixin
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Q
from django.shortcuts import get_object_or_404, redirect, render
from django.urls.base import reverse_lazy
from django.views.generic import ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator

from blog.models import Post
from category.forms import CategoryForm
from category.models import Category


class CategoryListView(LoginRequiredMixin, ListView):
    model = Category
    context_object_name = 'categories'
    template_name = 'dashboard/category/list.html'
    paginate_by=10
    
    # it is for pagination
    def get_queryset(self):
        filter_val=self.request.GET.get("filter","")
        order_by=self.request.GET.get("orderby","id")
        if filter_val!="":
            cat=Category.objects.filter(Q(title__contains=filter_val) | Q(description__contains=filter_val)).order_by(order_by)
        else:
            cat=Category.objects.all().order_by(order_by)

        return cat

    def get_context_data(self,**kwargs):
        context=super(CategoryListView,self).get_context_data(**kwargs)
        context["filter"]=self.request.GET.get("filter","")
        context["orderby"]=self.request.GET.get("orderby","id")
        context["all_table_fields"]=Category._meta.get_fields()
        context['segment'] = "لیست دسته بندی"
        return context



@method_decorator(csrf_exempt, name='dispatch')
class CreateCategoryView(SuccessMessageMixin, PermissionRequiredMixin,LoginRequiredMixin, CreateView):
    model = Category
    permission_required = "category.create_category"
    template_name = 'dashboard/category/create.html'
    form_class = CategoryForm
    success_url = reverse_lazy('category:cat-list')
    success_message = "دسته بندی با موفقیت ایجاد گردید!"

    def handle_no_permission(self):
        messages.warning(self.request, " شما اجازه دسترسی به این صفحه رو ندارید")
        return redirect("dashboard:home")

    def get_context_data(self,**kwargs):
        context=super().get_context_data(**kwargs)
        context['segment'] = "ایجاد دسته بندی"
        return context


@method_decorator(csrf_exempt, name='dispatch')
class DeleteCategoryView(SuccessMessageMixin, PermissionRequiredMixin, LoginRequiredMixin,DeleteView):
    model = Category
    permission_required = "category.delete_category"
    template_name = 'dashboard/category/list.html'
    success_url = reverse_lazy('category:cat-list')
   

    def handle_no_permission(self):
        messages.warning(self.request, " شما اجازه دسترسی به این صفحه رو ندارید")
        return redirect("dashboard:home")
    
    def get(self, request, *args, **kwargs):
        pk=kwargs.get("pk")
        if pk is not None:
            category_object = Category.objects.get_queryset().get(pk= pk)
            if category_object is not None:
                category_object.delete()
                messages.success(request, "دسته بندی شما با موفقیت حذف گردید!")
                return redirect('category:cat-list')
        return redirect('dashboard/category/list.html')
       
       
@method_decorator(csrf_exempt, name='dispatch')
class CategoryUpdateView(SuccessMessageMixin, PermissionRequiredMixin,LoginRequiredMixin, UpdateView):
    model = Category
    template_name = 'dashboard/category/edit.html'
    form_class = CategoryForm
    pk_url_kwarg = 'pk'
    success_message="کتگوری با موفقیت ویرایش شد!"
    success_url = reverse_lazy('category:cat-list')
    permission_required = "category.update_category"


    def handle_no_permission(self):
        messages.warning(self.request, " شما اجازه دسترسی به این صفحه رو ندارید")
        return redirect("dashboard:home")


@csrf_exempt
def posts_list_by_category(request, slug=None, *args, **kwargs):

    category = None
    posts = Post.objects.filter(status=1)
    if slug:
        category = get_object_or_404(Category, slug=slug)
        posts = posts.filter(category=category)
        page = request.GET.get('page', 1)

        paginator = Paginator(posts, 15)
        try:
            page_obj = paginator.page(page)
        except PageNotAnInteger:
            page_obj = paginator.page(1)
        except EmptyPage:
            page_obj = paginator.page(paginator.num_pages)
    return render(request,
                  'frontend/posts/list_category.html',
                  {'page_obj':page_obj, 'title':'دسته بندی ها'})



templates/dashboard/category/create.html
{% extends "dashboard/layouts/base.html" %}
{% block content %}
{% if messages %}
{% for message in messages %}
<div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
  <div {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</div>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}
{% endif %}
{% include "dashboard/includes/_headnav.html" %}
<div class="card border-0 shadow mb-4">
  <div class="card-body">
    <div class="table-responsive">
        <form method="post" action="" class="mt-4" enctype="multipart/form-data" novalidate>
            {% csrf_token %} 
            {% include 'dashboard/includes/form.html' %}
            <div class="d-grid mt-4">
                <button type="submit" name="login" class="btn btn-gray-800">ارسال</button>
            </div>
        </form>
    </div>
  </div>
</div>
{% endblock content %}
{% block javascripts %}
<script src="https://cdn.ckeditor.com/4.17.2/standard/ckeditor.js"></script>
<script>
  CKEDITOR.replace('content');
</script>

{% endblock javascripts %}

templates/dashboard/category/list.html
{% extends "dashboard/layouts/base.html" %}
{% load static %}
{% block content %}
{% if messages %}
{% for message in messages %}
<div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
  <div {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</div>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}
{% endif %}
{% include "dashboard/includes/_headnav.html" %}

<div class="card border-0 shadow mb-4">
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-centered table-nowrap mb-0 rounded">
        <thead class="thead-light">
          <tr>
            <th class="border-0 rounded-start">#</th>
            <th class="border-0">تصویر</th>
            <th class="border-0">متن</th>
            <th class="border-0">اسلاگ</th>
            <th class="border-0">وضعیت</th>
            <th class="border-0">تاریخ انتشار</th>
            <th class="border-0">حذف / ویرایش</th>
          </tr>
        </thead>
        <tbody>
          {% for category in categories %}
          {% if user.is_superuser%}
          <tr>
            <td><a href="#" class="text-primary fw-bold">{{ category.id}}</a></td>
            {% if category.banner %}
            <td><img src="{{ category.banner.url }}" class="rounded-circle" width=60 /></td>
            {% else %}
            <td><img src="{% static '/assets/backend/images/course-01.jpg' %}" class="rounded-circle" width=70 /></td>
            {% endif %}
            <td>{{ category.title}}</td>
            <td>{{ category.slug}}</td>
            <td>{% if category.status == 1 %}<img
                src="https://img.icons8.com/fluency/35/null/door-sensor-checked.png" />{% else %}<img
                src="https://img.icons8.com/avantgarde/35/null/no-edit.png" /> {% endif %}</td>
            <td class="text-success">
              <div class="d-flex align-items-center">
                <svg class="icon icon-xs me-1" fill="currentColor" viewBox="0 0 20 20"
                  xmlns="http://www.w3.org/2000/svg">
                  <path fill-rule="evenodd"
                    d="M14.707 12.707a1 1 0 01-1.414 0L10 9.414l-3.293 3.293a1 1 0 01-1.414-1.414l4-4a1 1 0 011.414 0l4 4a1 1 0 010 1.414z"
                    clip-rule="evenodd"></path>
                </svg>
                <span class="fw-bold">{{ category.published }}</span>
              </div>
            </td>
            {% if request.user.is_authenticated%}
            <td>
              <a href="{% url 'category:cat-update' category.pk %}"><img
                  src="https://img.icons8.com/external-flaticons-lineal-color-flat-icons/25/null/external-edit-web-flaticons-lineal-color-flat-icons-9.png" /></a>
              <form method="POST" action="{% url 'category:cat-list' %}">
                {% csrf_token %}
                <a href="{% url 'category:cat-delete' category.pk %}"><img
                    src="https://img.icons8.com/external-flatart-icons-solid-flatarticons/30/F25081/external-trash-office-flatart-icons-solid-flatarticons.png" /></a>
              </form>
              </form>
            </td>
            {% endif %}
          </tr>
          {% endif %}
          {% endfor %}
        </tbody>
      </table>
    </div>
    <div class="card-body">
      <nav aria-label="Page navigation example">
        <ul class="pagination">
          {% if page_obj.has_previous %}
          <li class="page-item"><a class="page-link"
              href="{% url 'category:cat-list' %}' %}?filter={{ filter }}&orderby={{ orderby }}&page={{ page_obj.previous_page_number }}">Previous</a>
          </li>
          {% else %}
          <li class="page-item disabled"><a class="page-link" href="#">قبل</a></li>
          {% endif %}
          {% for i in paginator.page_range %}
          <li class="page-item {% if i == page_obj.number %}active{% endif %}"><a class="page-link"
              href="{% url 'category:cat-list' %}' %}?filter={{ filter }}&orderby={{ orderby }}&page={{ i }}">{{i}}</a></li>
          {% endfor %}
          {% if page_obj.has_next %}
          <li class="page-item"><a class="page-link"
              href="{% url 'category:cat-list' %}' %}?filter={{ filter }}&orderby={{ orderby }}&page={{ page_obj.next_page_number }}">Next</a>
          </li>
          {% else %}
          <li class="page-item disabled"><a class="page-link" href="#">بعد</a></li>
          {% endif %}
    </div>
  </div>
</div>
  {% endblock content %}
  {% block javascripts %}{% endblock javascripts %}