accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import re_path

from accounts import views as accounts_views

app_name = "accounts"
urlpatterns = [
    re_path(r'^signup/$', accounts_views.signup, name='signup'),
        ]

api/urls.py
from django.urls import include, re_path
from rest_framework import routers

from api.views import (APICategoryViewSet, APIPostViewSet, APIProfileViewSet,
                       APISubCategoryViewSet, APITagViewSet, NewsLetterView,
                       UserViewSet)
from blog.models import Post

router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'tags', APITagViewSet)
router.register(r'posts', APIPostViewSet)
router.register(r'categories', APICategoryViewSet)
router.register(r'subcategories', APISubCategoryViewSet)
router.register(r'profile', APIProfileViewSet)



urlpatterns = [
    re_path(r'^', include(router.urls)),
    re_path(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    re_path(r'^newsletter/',NewsLetterView.as_view(), name = "subscribe"),

    # re_path(r'^posts/',APIPostListCreateView.as_view(), name = "list"),
    # re_path(r'^post/(?P<pk>[0-9a-f]{8}-[0-9a-f]{4}-[0-5][0-9a-f]{3}-[089ab][0-9a-f]{3}-[0-9a-f]{12})/$', APIPostDetailView.as_view(), name = 'detail'),
    # re_path(r'^post/(?P<pk>[0-9a-f]{8}-[0-9a-f]{4}-[0-5][0-9a-f]{3}-[089ab][0-9a-f]{3}-[0-9a-f]{12})/edit/$', APIPostUpdateDestroyDetailView.as_view(), name = 'edit'),
    # re_path(r'^tags/', APITagListCreateView.as_view(), name = 'list'),
    # re_path(r'^tag/(?P<pk>[-\d]+)/', APITagDetailView.as_view(), name = 'detail'),
    # re_path(r'^tag/(?P<pk>[-\d]+)/edit/$', APITagEditView.as_view(), name = 'edit'),
    
]

contact/urls.py
from django.conf.urls.static import static
from django.urls import re_path

from insurance import settings

from . import views

app_name = 'contact'

urlpatterns = [
    re_path(r'^list/', views.ListContactView.as_view(), name = 'contact-list'), 
    re_path(r'^create/', views.CreateContactView.as_view(), name = 'contact-create'), 
    re_path(r'^(?P<pk>[0-9a-f]{8}-[0-9a-f]{4}-[0-5][0-9a-f]{3}-[089ab][0-9a-f]{3}-[0-9a-f]{12})/delete/', views.DeleteContactView.as_view(), name = 'delete'),
    re_path(r'^(?P<pk>[0-9a-f]{8}-[0-9a-f]{4}-[0-5][0-9a-f]{3}-[089ab][0-9a-f]{3}-[0-9a-f]{12})/show/', views.ContactShowView.as_view(), name='show'),

]
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)+static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

insurance/urls.py

from dj_rest_auth.registration.views import ConfirmEmailView, VerifyEmailView
from dj_rest_auth.views import PasswordResetConfirmView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path, re_path

from insurance import views

urlpatterns = [
    re_path(r'^i18n/', include('django.conf.urls.i18n')),
    re_path(r'^', include('accounts.urls',namespace='accounts')),
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^', include('blog.urls')),
    re_path(r'^new/', include('news.urls')),
    re_path(r'^search/', include('search.urls')),
    re_path(r'^dashboard/', include('dashboard.urls')),
    re_path(r'^tag/', include('tag.urls')),
    re_path(r'^about/', include('aboutus.urls' ,namespace='about_us')),
    re_path(r'^settings/', include('aboutus.urls')),
    re_path(r'^team/', include('team.urls')),
    re_path(r'^category/', include('category.urls')),
    re_path(r'^contact/', include('contact.urls')),
    re_path(r'^faq/', include('faq.urls')),
    re_path(r'^customer-feedback/', include('feedback.urls')),
    re_path(r'^user/', include('users.urls')),
    re_path(r'^frontend/', include('renewal.urls')),
    re_path(r'^ticket/', include('tickets.urls')),
    re_path(r'^social-auth/', include('social_django.urls', namespace='social')),
    re_path(r'^ratings/', include('star_ratings.urls', namespace='ratings')),
    re_path(r'^', include('django.contrib.auth.urls')),
    re_path(r'^__debug__/', include('debug_toolbar.urls')),
    re_path(r'^accounts/login/$', auth_views.LoginView.as_view(template_name='frontend/accounts/login.html'), name='login'),
    re_path(r'^accounts/logout/$', auth_views.LogoutView.as_view(), name='logout'),
    re_path(r'^accounts/reset/$',
        auth_views.PasswordResetView.as_view(
            template_name='frontend/accounts/password_reset.html',
            html_email_template_name='frontend/accounts/password_reset_email.html',
            email_template_name='frontend/accounts/password_reset_email.html',
            subject_template_name='frontend/accounts/password_reset_subject.txt'
        ),
        name='password_reset'),
    re_path(r'^accounts/reset/done/$',
        auth_views.PasswordResetDoneView.as_view(template_name='frontend/accounts/password_reset_done.html'),
        name='password_reset_done'),
    re_path(r'^accounts/reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        auth_views.PasswordResetConfirmView.as_view(template_name='frontend/accounts/password_reset_confirm.html'),
        name='password_reset_confirm'),
    re_path(r'^accounts/reset/complete/$',
        auth_views.PasswordResetCompleteView.as_view(template_name='frontend/accounts/password_reset_complete.html'),
        name='password_reset_complete'),
    re_path(r'^settings/password/done/$',
        auth_views.PasswordChangeDoneView.as_view(template_name='frontend/accounts/password_change_done.html'),
        name='password_change_done'),
    re_path(r'^.*\.*', views.pages, name='pages'),   

    #######################
        ### DRF ###
    ####################### 
    # re_path(r'^api/', include('api.urls')),
    # re_path(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    # re_path(r'^api/v1/rest-auth/', include('dj_rest_auth.urls')),
    # re_path(r'^api/v1/rest-auth/registration/', include('dj_rest_auth.registration.urls')),
    # re_path(r'^api/v1/rest-auth/account-confirm-email/(?P<key>[-:\w]+)/$',  ConfirmEmailView.as_view(), name='account_confirm_email'),
    # re_path(r'^api/v1/rest-auth/account-confirm-email/', VerifyEmailView.as_view(), name='account_email_verification_sent'),
    # re_path(r'^api/v1/rest-auth/password/reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_URL)


users/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path

from . import views

app_name = 'user'

urlpatterns = [

    re_path(r'^create/', views.ProfileView.as_view(), name='user-create'),
    re_path(r'^list/', views.UserListView.as_view(), name = 'user-list'), 
    re_path(r'^(?P<pk>[-\w]+)/delete/', views.DeleteUserView.as_view(), name = 'user-delete'),
    re_path(r'^edit/(?P<pk>[-\d]+)/$', views.ProfileUpdateView.as_view(), name='user-update'),
    re_path(r'^password-change/', views.ChangePasswordView.as_view(), name='password_change'),
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)+static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

accounts/models.py
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.core.validators import validate_email
from django.db import models
from django.utils.translation import gettext_lazy as _

from painless.models.validations import validate_phone_number


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """Create and save a User with the given email and password."""
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user
    

    def create_user(self, email, password=None, **extra_fields):
        """Create and save a regular User with the given email and password."""
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)
    

    def create_superuser(self, email, password, **extra_fields):
        """Create and save a SuperUser with the given email and password."""
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')
            

        return self._create_user(email, password, **extra_fields)



class IPAddress(models.Model):
    ip_address = models.GenericIPAddressField(verbose_name='آدرس IP')
    create = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ بازدید')
 
    def __str__(self):
        return self.ip_address
 
    class Meta:
        verbose_name = 'بازدید'
        verbose_name_plural = 'بازدیدها'




class User(AbstractUser):
    username = None
    email = models.EmailField(_('ایمیل'),unique=True, validators = [validate_email])
    mobile = models.CharField(_('موبایل'),max_length = 12, validators= [validate_phone_number])
    
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()

    class Meta:
        verbose_name = _('کاربر')
        verbose_name_plural = _('کاربران')

    def get_full_name(self):
        return self.email

    def get_short_name(self):
        return self.email



accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()


class SignUpForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')

accounts/views.py
from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login
from django.shortcuts import redirect, render
from django.views.decorators.csrf import csrf_exempt

from .forms import SignUpForm


@csrf_exempt
def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            email = form.cleaned_data.get('email')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(email=email, password=raw_password)
            auth_login(request, user)
            # celery.delay(user = user)
            return redirect('dashboard:home')
    else:
        form = SignUpForm()
    return render(request, 'frontend/accounts/register.html', {'form': form, 'title':"ثبت نام"})







templates/frontend/accounts/login.html
{% extends "frontend/shared/home.html" %}
{% block title %}ورود{% endblock %}

{% block body %}
{% include 'frontend/partials/_head.html' %}
<section class="user-area-all-style log-in-area ptb-100">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="contact-form-action">
                    <div class="form-heading text-center">
                        <h3 class="form-title">وارد حساب کاربری شوید!</h3>
                        <p class="form-desc">یا با شبکه اجتماعی وارد شوید.</p>
                    </div>
                    <form method="post">
                        <div class="row">

                            <div class="col-12">
                                <form method="post" action="" class="mt-4" novalidate>
                                    {% csrf_token %}
                                    {% include 'dashboard/includes/form.html' %}
                            </div>

                            <div class="col-lg-6 col-sm-6 form-condition">
                                <div class="agree-label">
                                    <input type="checkbox" id="chb1">
                                    <label for="chb1">
                                        مرا بخاطر بسپار
                                    </label>
                                </div>
                            </div>
                            <div class="col-lg-6 col-sm-6">
                                <a class="forget" href="{% url 'password_reset' %}">فراموشی گذرواژه؟</a>
                            </div>
                            <div class="col-lg-12 col-md-6 col-sm-12">
                                <button class="default-btn btn-block" type="submit">
                                    وارد شوید
                                </button>
                            </div>
                            <div class="col-lg-12 col-md-6 col-sm-12">
                                <a href="{% url 'social:begin' 'google-oauth2' %}" class="btn btn-danger btn-block">
                                    گوگل + </a>
                            </div>
                    </form>
                    <div class="col-12">
                        <p class="account-desc">
                            عضو نیستی؟
                            <a href="{% url 'accounts:signup' %}">عضویت</a>
                        </p>
                    </div>
                </div>
                </form>
            </div>
        </div>
    </div>
    </div>
</section>
{% endblock %}

templates/frontend/accounts/password_change.html
{% extends "frontend/shared/home.html" %}
{% block title %} {{ title }}{% endblock %}
{% load static %}
{% block body %}
{% include 'frontend/partials/_head.html' %}

<section class="user-area-all-style sign-up-area ptb-100">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="contact-form-action">
                    <div class="form-heading text-center">
                        <h3 class="form-title">{{ title }}</h3>
                    </div>
                    <form method="post"  novalidate>
                        {% csrf_token %}
                        {% include 'dashboard/includes/form.html' %}
                        <div class="col-12">
                            <button class="default-btn btn-block btn-two" type="submit">
                                ویرایش
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

templates/frontend/accounts/password_change_done.html
{% extends "frontend/shared/home.html" %}
{% block title %}تغییر رمز عبور با موفقیت انجام شد{% endblock %}


{% block body %}
{% include 'frontend/partials/_head.html' %}
<section class="user-area-all-style recover-password-area ptb-100">
  <div class="container">
      <div class="row">
          <div class="col-12">
              <div class="contact-form-action">
                  <div class="form-heading text-center">
                        <div class="alert alert-success" role="alert">
                        پسوردتان با موفقیت تغییر یافته است !
                        </div>
                  </div>
                      <div class="col-lg-6 col-md-6 col-sm-6">
                          <a class="now-log-in font-q" href="{% url 'login' %}">وارد شوید</a>
                      </div>
              </div>
          </div>
      </div>
  </div>

</section>

{% endblock %}



templates/frontend/accounts/password_reset.html
{% extends "frontend/shared/home.html" %}
{% block title %} فراموشی رمز عبور {% endblock %}
{% block body %}
{% include 'frontend/partials/_head.html' %}

<section class="user-area-all-style recover-password-area ptb-100">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="contact-form-action">
                    <div class="form-heading text-center">
                        <h3 class="form-title">بازیابی گذرواژه!</h3>
                        <p class="reset-desc">برای بازنشانی گذرواژه ، ایمیل حساب خود را
                            وارد کنید. سپس پیوندی به ایمیل برای بازنشانی گذرواژه
                            دریافت خواهید کرد. اگر در مورد تنظیم مجدد رمز عبور مشکلی
                            دارید <a href="{% url 'contact:contact-create' %}">تماس با ما.</a></p>
                    </div>
                    <form method="post" novalidate>
                        <div class="row">
                            <div class="col-12">
                                {% csrf_token %}
                                {% include 'dashboard/includes/form.html' %}
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-6">
                                <a class="now-log-in font-q" href="{% url 'login' %}">وارد شوید</a>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-6">
                                <p class="now-register">
                                    عضو نیستی
                                    <a class="font-q" href="{% url 'accounts:signup' %}">ثبت نام</a>
                                </p>
                            </div>
                            <div class="col-12">
                                <button class="default-btn btn-block" type="submit">
                                    بازیابی گذرواژه
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/frontend/accounts/password_reset_complete.html
{% extends "frontend/shared/home.html" %}
{% block title %}تغییر پسورد{% endblock %}

{% block body %}

{% include 'frontend/partials/_head.html' %}
<section class="user-area-all-style recover-password-area ptb-100">
  <div class="container">
      <div class="row">
          <div class="col-12">
              <div class="contact-form-action">
                  <div class="form-heading text-center">
                        <div class="alert alert-success" role="alert">
                            شما با موفقیت رمز عبور خود را تغییر دادید! اکنون می توانید وارد سیستم شوید.
                        </div>
                  </div>
                      <div class="col-lg-6 col-md-6 col-sm-6">
                          <a class="now-log-in font-q" href="{% url 'login' %}">وارد شوید</a>
                      </div>
              </div>
          </div>
      </div>
  </div>
</section>

{% endblock %}


templates/frontend/accounts/password_reset_confirm.html
{% extends "frontend/shared/home.html" %}
{% block title %}
{% if validlink %}
تغییر پسورد برای: {{ form.user.username }}
{% else %}
ریست کنید پسوردتان را
{% endif %}
{% endblock %}

{% block body %}
{% include 'frontend/partials/_head.html' %}
<section class="user-area-all-style log-in-area ptb-100">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <div class="contact-form-action">

          {% if validlink %}

          <form method="post" novalidate>
            {% csrf_token %}
            {% include 'dashboard/includes/form.html' %}
            <div class="col-lg-12 col-md-6 col-sm-12">
              <button class="default-btn btn-block" type="submit">
                تغییر پسورد
              </button>
            </div>
          </form>
          {% else %}

          <div class="alert alert-danger" role="alert">
            به نظر می‌رسد روی پیوند بازنشانی رمز عبور نامعتبر کلیک کرده‌اید. لطفا دوباره تلاش کنید.
          </div>
          <div class="col-lg-12">
            <a href="{% url 'password_reset' %}" class="default-btn btn-block">یک پیوند بازنشانی رمز عبور جدید درخواست
              کنید</a>
          </div>
          {% endif %}
          </form>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

templates/frontend/accounts/password_reset_done.html
{% extends "frontend/shared/home.html" %}

{% block title %}ریست کردن پسوردتان{% endblock %}

{% block body %}
{% include 'frontend/partials/_head.html' %}
<section class="user-area-all-style recover-password-area ptb-100">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <div class="contact-form-action">
          <div class="form-heading text-center">
            <div class="alert alert-success" role="alert">
              چک کنید ایمیلتان را برای ریست کردن پسوردتان.اگر آنرا دریافت نکردید در ۱ دقیقه لطفا فولدر اسپمتان را چک
              کنید !
            </div>
          </div>
          <div class="col-lg-6 col-md-6 col-sm-6">
            <a class="now-log-in font-q" href="{% url 'login' %}">وارد شوید</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

templates/frontend/accounts/password_reset_email.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

</head>

<body>
    <div>
        Hi there,

        شخصی برای آدرس ایمیل {{ email }} درخواست بازنشانی رمز عبور کرد.
        لینک زیر را دنبال کنید:
        {{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

        در صورتی که نام کاربری خود را فراموش کرده اید نام کاربری شما: {{ user.username }}


        اگر روی پیوند بالا کلیک نکردید، لطفاً URL را کپی و جایگذاری کنید
        در عوض در یک پنجره مرورگر جدید

        اگر این ایمیل را به اشتباه دریافت کرده اید، احتمالاً کاربر دیگری وارد شده است
        آدرس ایمیل شما به اشتباه هنگام تلاش برای بازنشانی رمز عبور. اگر این کار را نکردید
        درخواست را آغاز کنید، نیازی به انجام هیچ اقدام دیگری ندارید و می توانید با خیال راحت
        این ایمیل را نادیده بگیرید

        با تشکر،
    </div>
</body>

</html>

templates/frontend/accounts/profile.html
{% extends "frontend/shared/home.html" %}
{% load static %}
{% block body %}
{% include 'frontend/partials/_head.html' %}

<section class="user-area-all-style sign-up-area ptb-100">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="contact-form-action">
                    <div class="form-heading text-center">
                        <h3 class="form-title"> اطلاعات شخصی!</h3>
                    </div>
                
                    <form method="post" action="{% url 'user:user-update' user.pk %}" novalidate  enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'dashboard/includes/form.html' %}
                        
                        <div class="col-12">
                            <button class="default-btn btn-block btn-two" type="submit">
                               ویرایش
                            </button>
                        </div>

        
                </form>
            </div>
        </div>
    </div>
    </div>
</section>

{% endblock %}

templates/frontend/accounts/register.html
{% extends "frontend/shared/home.html" %}
{% block body %}

{% include 'frontend/partials/_head.html' %}
<section class="user-area-all-style sign-up-area ptb-100">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="contact-form-action">
                    <div class="form-heading text-center">
                        <h3 class="form-title">ایجاد حساب کاربری!</h3>
                        <p class="form-desc">یا با شبکه اجتماعی وارد شوید.</p>
                    </div>
                    <form method="post">
                        <div class="row">
                            <div class="col-md-12 col-sm-12">
                                <form method="post" action="" novalidate>
                                    {% csrf_token %} {% include 'dashboard/includes/form.html' %}
                               
                            </div>
                            <div class="col-12">
                                <button class="default-btn btn-block" type="submit">
                                    ثبت نام
                                </button>
                            </div>
                            <div class="col-12">
                                <p class="account-desc">
                                    حساب کاربری داری؟
                                    <a href="{% url 'login' %}"> ورود</a>
                                </p>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock body %}