api/urls.py
from django.urls import include, re_path
from rest_framework import routers

from api.views import (APICategoryViewSet, APIPostViewSet, APIProfileViewSet,
                       APISubCategoryViewSet, APITagViewSet, NewsLetterView,
                       UserViewSet)
from blog.models import Post

router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'tags', APITagViewSet)
router.register(r'posts', APIPostViewSet)
router.register(r'categories', APICategoryViewSet)
router.register(r'subcategories', APISubCategoryViewSet)
router.register(r'profile', APIProfileViewSet)



urlpatterns = [
    re_path(r'^', include(router.urls)),
    re_path(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    re_path(r'^newsletter/',NewsLetterView.as_view(), name = "subscribe"),

    # re_path(r'^posts/',APIPostListCreateView.as_view(), name = "list"),
    # re_path(r'^post/(?P<pk>[0-9a-f]{8}-[0-9a-f]{4}-[0-5][0-9a-f]{3}-[089ab][0-9a-f]{3}-[0-9a-f]{12})/$', APIPostDetailView.as_view(), name = 'detail'),
    # re_path(r'^post/(?P<pk>[0-9a-f]{8}-[0-9a-f]{4}-[0-5][0-9a-f]{3}-[089ab][0-9a-f]{3}-[0-9a-f]{12})/edit/$', APIPostUpdateDestroyDetailView.as_view(), name = 'edit'),
    # re_path(r'^tags/', APITagListCreateView.as_view(), name = 'list'),
    # re_path(r'^tag/(?P<pk>[-\d]+)/', APITagDetailView.as_view(), name = 'detail'),
    # re_path(r'^tag/(?P<pk>[-\d]+)/edit/$', APITagEditView.as_view(), name = 'edit'),
    
]

contact/urls.py
from django.conf.urls.static import static
from django.urls import re_path

from insurance import settings

from . import views

app_name = 'contact'

urlpatterns = [
    re_path(r'^list/', views.ListContactView.as_view(), name = 'contact-list'), 
    re_path(r'^create/', views.CreateContactView.as_view(), name = 'contact-create'), 
    re_path(r'^(?P<pk>[0-9a-f]{8}-[0-9a-f]{4}-[0-5][0-9a-f]{3}-[089ab][0-9a-f]{3}-[0-9a-f]{12})/delete/', views.DeleteContactView.as_view(), name = 'delete'),
    re_path(r'^(?P<pk>[0-9a-f]{8}-[0-9a-f]{4}-[0-5][0-9a-f]{3}-[089ab][0-9a-f]{3}-[0-9a-f]{12})/show/', views.ContactShowView.as_view(), name='show'),

]
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)+static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

dashboard/urls.py
from django.contrib.sitemaps.views import sitemap
from django.urls import re_path

from dashboard.sitemaps import PostSitemap, StaticViewSitemap

from . import views

sitemaps = {
    'static': StaticViewSitemap,
    'post':PostSitemap
}

app_name = 'dashboard'

urlpatterns = [
    re_path(r'home/',views.DashboardView.as_view(), name = 'home'), 
    re_path(r'^password/$', 
        views.ChangePasswordView.as_view(),name='password_change'),
    
    re_path(r'^list-post/$', views.PostListView.as_view(), name = 'post-list'), 
    re_path(r'^create-post/$', views.PostCreateView.as_view(), name = 'post-create'), 
    re_path(r'^(?P<pk>[0-9a-f]{8}-[0-9a-f]{4}-[0-5][0-9a-f]{3}-[089ab][0-9a-f]{3}-[0-9a-f]{12})/delete-post/$', views.PostDeleteView.as_view(), name = 'post-delete'),
    re_path(r'^(?P<pk>[0-9a-f]{8}-[0-9a-f]{4}-[0-5][0-9a-f]{3}-[089ab][0-9a-f]{3}-[0-9a-f]{12})/edit-post/$', views.PostUpdateView.as_view(), name='post-update'),
    re_path(r'^list-news/$', views.NewListView.as_view(), name = 'new-list'), 
    re_path(r'^create-news/$', views.NewCreateView.as_view(), name = 'new-create'), 
    re_path(r'^(?P<pk>[0-9a-f]{8}-[0-9a-f]{4}-[0-5][0-9a-f]{3}-[089ab][0-9a-f]{3}-[0-9a-f]{12})/delete-new/$', views.NewDeleteView.as_view(), name = 'new-delete'),
    re_path(r'^(?P<pk>[0-9a-f]{8}-[0-9a-f]{4}-[0-5][0-9a-f]{3}-[089ab][0-9a-f]{3}-[0-9a-f]{12})/edit-new/$', views.NewUpdateView.as_view(), name='new-update'),
    re_path(r'^sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),

]

feedback/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path

from . import views

app_name = 'customer-feedback'

urlpatterns = [
    re_path(r'^', views.CustomerFeedbackListView.as_view(), name = 'list'), 
]
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)+static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
   

insurance/urls.py

from dj_rest_auth.registration.views import ConfirmEmailView, VerifyEmailView
from dj_rest_auth.views import PasswordResetConfirmView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path, re_path

from insurance import views

urlpatterns = [
    re_path(r'^i18n/', include('django.conf.urls.i18n')),
    re_path(r'^', include('accounts.urls',namespace='accounts')),
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^', include('blog.urls')),
    re_path(r'^new/', include('news.urls')),
    re_path(r'^search/', include('search.urls')),
    re_path(r'^dashboard/', include('dashboard.urls')),
    re_path(r'^tag/', include('tag.urls')),
    re_path(r'^about/', include('aboutus.urls' ,namespace='about_us')),
    re_path(r'^settings/', include('aboutus.urls')),
    re_path(r'^team/', include('team.urls')),
    re_path(r'^category/', include('category.urls')),
    re_path(r'^contact/', include('contact.urls')),
    re_path(r'^faq/', include('faq.urls')),
    re_path(r'^customer-feedback/', include('feedback.urls')),
    re_path(r'^user/', include('users.urls')),
    re_path(r'^frontend/', include('renewal.urls')),
    re_path(r'^ticket/', include('tickets.urls')),
    re_path(r'^social-auth/', include('social_django.urls', namespace='social')),
    re_path(r'^ratings/', include('star_ratings.urls', namespace='ratings')),
    re_path(r'^', include('django.contrib.auth.urls')),
    re_path(r'^__debug__/', include('debug_toolbar.urls')),
    re_path(r'^accounts/login/$', auth_views.LoginView.as_view(template_name='frontend/accounts/login.html'), name='login'),
    re_path(r'^accounts/logout/$', auth_views.LogoutView.as_view(), name='logout'),
    re_path(r'^accounts/reset/$',
        auth_views.PasswordResetView.as_view(
            template_name='frontend/accounts/password_reset.html',
            html_email_template_name='frontend/accounts/password_reset_email.html',
            email_template_name='frontend/accounts/password_reset_email.html',
            subject_template_name='frontend/accounts/password_reset_subject.txt'
        ),
        name='password_reset'),
    re_path(r'^accounts/reset/done/$',
        auth_views.PasswordResetDoneView.as_view(template_name='frontend/accounts/password_reset_done.html'),
        name='password_reset_done'),
    re_path(r'^accounts/reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        auth_views.PasswordResetConfirmView.as_view(template_name='frontend/accounts/password_reset_confirm.html'),
        name='password_reset_confirm'),
    re_path(r'^accounts/reset/complete/$',
        auth_views.PasswordResetCompleteView.as_view(template_name='frontend/accounts/password_reset_complete.html'),
        name='password_reset_complete'),
    re_path(r'^settings/password/done/$',
        auth_views.PasswordChangeDoneView.as_view(template_name='frontend/accounts/password_change_done.html'),
        name='password_change_done'),
    re_path(r'^.*\.*', views.pages, name='pages'),   

    #######################
        ### DRF ###
    ####################### 
    # re_path(r'^api/', include('api.urls')),
    # re_path(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    # re_path(r'^api/v1/rest-auth/', include('dj_rest_auth.urls')),
    # re_path(r'^api/v1/rest-auth/registration/', include('dj_rest_auth.registration.urls')),
    # re_path(r'^api/v1/rest-auth/account-confirm-email/(?P<key>[-:\w]+)/$',  ConfirmEmailView.as_view(), name='account_confirm_email'),
    # re_path(r'^api/v1/rest-auth/account-confirm-email/', VerifyEmailView.as_view(), name='account_email_verification_sent'),
    # re_path(r'^api/v1/rest-auth/password/reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_URL)


contact/models.py
import uuid

from django.core.validators import validate_email
from django.db import models
from django.utils.translation import gettext_lazy as _


class Contact(models.Model):
    uid = models.UUIDField(primary_key = True, default = uuid.uuid4, editable = False)
    subject = models.CharField(_("موضوع"),max_length = 128)
    email = models.EmailField(_('ایمیل'),unique=True, validators = [validate_email])
    content = models.TextField(_("پیام"))
    created = models.DateTimeField(auto_now_add=True)

    objects = models.Manager()

    class Meta:
        ordering = ['-created', 'subject']
        verbose_name = _('تماس')
        verbose_name_plural = _('تماسها')
        get_latest_by = ['-created']

    def __str__(self):
        return self.subject




class Location(models.Model):
    address = models.CharField(_('آدرس'),max_length=200, null = True)
    date = models.DateTimeField(auto_now_add = True)
    class Meta:
        verbose_name = _('نقشه')
        verbose_name_plural = _('نقشه')

    def __str__(self):
        return self.address

dashboard/models.py
from django.db import models

# Create your models here.

contact/forms.py
from django import forms

from contact.models import Contact


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = "__all__"

contact/views.py
import folium
import geocoder
from django.contrib import messages
from django.contrib.auth.mixins import (LoginRequiredMixin,
                                        PermissionRequiredMixin)
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import redirect, render
from django.urls.base import reverse_lazy
from django.views.generic import ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from contact.forms import ContactForm
from contact.models import Contact, Location
from contact.tasks import my_first_task


class ListContactView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = Contact
    permission_required = "contact.view_contact"
    context_object_name = 'contacts'
    template_name = 'dashboard/contact/list.html'
    paginate_by = 10

    def handle_no_permission(self):
        messages.warning(self.request, " شما اجازه دسترسی به این صفحه رو ندارید")
        return redirect("dashboard:home")


    def get_queryset(self):
        filter_val = self.request.GET.get("filter", "")
        order_by = self.request.GET.get("orderby", "pk")
        if filter_val != "":
            contact = Contact.objects.filter(Q(title__contains=filter_val) | Q(
                description__contains=filter_val)).order_by(order_by)
        else:
            contact = Contact.objects.all().order_by(order_by)

        return contact

    def get_context_data(self, **kwargs):
        context = super(ListContactView, self).get_context_data(**kwargs)
        context["filter"] = self.request.GET.get("filter", "")
        context["orderby"] = self.request.GET.get("orderby", "pk")
        context["all_table_fields"] = Contact._meta.get_fields()
        context["segment"] = "لیست تماس"
        return context
        

@method_decorator(csrf_exempt, name='dispatch')
class CreateContactView(SuccessMessageMixin , CreateView):
    def post(self, request, *args, **kwargs):
            if request.method == 'POST':
                form = ContactForm(request.POST)
                if form.is_valid():
                    form = form.save(commit=False)
                    my_first_task.delay(15)
                    form.save()
                    messages.success(request,
                                    "پیام شما با موفقیت ارسال گردید !")
                    return redirect("contact:contact-create")
            else:
                form = ContactForm()
            return render(request, 'frontend/contact/create.html',
                        {'form': form , "segment":"تماس با ما"} 
                    )


    def get(self, request, **kwargs):
        address = Location.objects.all().last()
        location = geocoder.osm(address)
        lat = location.lat
        lng = location.lng
        country = location.country
        map = folium.Map(location=[19,-12], zoom_start=2)
    
        folium.Marker([lat,lng],tooltip="click for more",popup = country).add_to(map)
        map = map._repr_html_()
        return render(request, 'frontend/contact/create.html',
                        {'map':map, 'segment': 'تماس با ما'}
                        )



@method_decorator(csrf_exempt, name='dispatch')
class DeleteContactView(SuccessMessageMixin, PermissionRequiredMixin, LoginRequiredMixin, DeleteView):
    model = Contact
    permission_required = "contact.delete_contact"
    template_name = 'dashboard/contact/list.html'
    success_url = reverse_lazy('contact:list')
    success_message = "Contact Delete successfully"


    def handle_no_permission(self):
        messages.warning(self.request, " شما اجازه دسترسی به این صفحه رو ندارید")
        return redirect("dashboard:home")

    def get(self, request, *args, **kwargs):
        pk=kwargs.get("pk")
        if pk is not None:
            Contact_object = Contact.objects.get_queryset().filter(pk= pk)
            if Contact_object is not None:
                Contact_object.delete()
                messages.success(request, 'پست شما با موفقیت حذف گردید') 
                return redirect('contact:contact-list')
        return redirect('dashboard/Contact/list.html')
       


class ContactShowView(SuccessMessageMixin,PermissionRequiredMixin, LoginRequiredMixin,UpdateView):
    permission_required = "contact.update_contact"
    model = Contact
    template_name = 'dashboard/contact/show.html'
    fields = "__all__" 
    success_url = reverse_lazy('contact:contact-list')
    
    def handle_no_permission(self):
        messages.warning(self.request, " شما اجازه دسترسی به این صفحه رو ندارید")
        return redirect("dashboard:home")


templates/dashboard/contact/create.html
{% extends "dashboard/layouts/base.html" %} {% block title %}Create Tag{% endblock%}

{% block stylesheets %}{% endblock stylesheets %} {% block content %}

<div class="py-4">
  <nav aria-label="breadcrumb" class="d-none d-md-inline-block">
    <ol class="breadcrumb breadcrumb-dark breadcrumb-transparent">
      <li class="breadcrumb-item">
        <a href="#">
          <svg
            class="icon icon-xxs"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6"
            ></path>
          </svg>
        </a>
      </li>
      <li class="breadcrumb-item"><a href="#">Tables</a></li>
      <li class="breadcrumb-item active" aria-current="page">
        Bootstrap tables
      </li>
    </ol>
  </nav>
</div>

<div class="card border-0 shadow mb-4">
  <div class="card-body">
    <div class="table-responsive">
        <form method="post" action="" class="mt-4" enctype="multipart/form-data" novalidate>
            {% csrf_token %} 
            {% include 'dashboard/includes/form.html' %}
        
            <div class="d-grid mt-4">
                <button type="submit" name="login" class="btn btn-gray-800">Submit</button>
            </div>
        </form>
    </div>
  </div>
</div>

{% endblock content %} {% block javascripts %}{% endblock javascripts %}

templates/dashboard/contact/list.html
{% extends "dashboard/layouts/base.html" %}
{% block content %}
{% if messages %}
{% for message in messages %}
<div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
  <div {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</div>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}
{% endif %}
{% include "dashboard/includes/_headnav.html" %}


<div class="card border-0 shadow mb-4">
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-centered table-nowrap mb-0 rounded">
        <thead class="thead-light">
          <tr>
            <th class="border-0 rounded-start">#</th>
            <th class="border-0">موضوع</th>
            <th class="border-0">ایمیل</th>
            <th class="border-0">پیام</th>
            <th class="border-0">تاریخ ایجاد</th>
            <th class="border-0">تاریخ اپدیت</th>
            <th class="border-0">حذف / اپدیت</th>
          </tr>
        </thead>
        <tbody>
          {% for contact in contacts %}
          {% if user.is_superuser %}
          <tr>
            <td><a href="#" class="text-primary fw-bold">{{ forloop.counter }}</a></td>

            <td>{{ contact.subject}}</td>
            <td>{{ contact.email}}</td>
            <td>{{ contact.content|truncatechars:10 }}</td>
            <td>{{ contact.created }}</td>
            <td class="text-success">
              <div class="d-flex align-items-center">
                <svg class="icon icon-xs me-1" fill="currentColor" viewBox="0 0 20 20"
                  xmlns="http://www.w3.org/2000/svg">
                  <path fill-rule="evenodd"
                    d="M14.707 12.707a1 1 0 01-1.414 0L10 9.414l-3.293 3.293a1 1 0 01-1.414-1.414l4-4a1 1 0 011.414 0l4 4a1 1 0 010 1.414z"
                    clip-rule="evenodd"></path>
                </svg>
                <span class="fw-bold">{{contact.created}}</span>
              </div>
            </td>
            {% if request.user.is_authenticated %}
            <td>
              <a href="{% url 'contact:show' contact.pk %}"><img
                  src="https://img.icons8.com/bubbles/30/000000/edit.png" /></a>
              <form method="POST" action="{% url 'contact:list' %}">
                {% csrf_token %}
                <a href="{% url " contact:delete" contact.pk %}"><img
                    src="https://img.icons8.com/external-flatart-icons-solid-flatarticons/30/F25081/external-trash-office-flatart-icons-solid-flatarticons.png" /></a>
              </form>
            </td>
            {% endif %}
          </tr>
          {% endif %}
          {% endfor %}
        </tbody>
      </table>
    </div>
    <div class="card-body">
      <nav aria-label="Page navigation example">
        <ul class="pagination">
          {% if page_obj.has_previous %}
          <li class="page-item"><a class="page-link"
              href="{% url 'contact:contact-list' %}' %}?filter={{ filter }}&orderby={{ orderby }}&page={{ page_obj.previous_page_number }}">Previous</a>
          </li>
          {% else %}
          <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
          {% endif %}
          {% for i in paginator.page_range %}
          <li class="page-item {% if i == page_obj.number %}active{% endif %}"><a class="page-link"
              href="{% url 'contact:contact-list' %}' %}?filter={{ filter }}&orderby={{ orderby }}&page={{ i }}">{{ i }}</a>
          </li>
          {% endfor %}
          {% if page_obj.has_next %}
          <li class="page-item"><a class="page-link"
              href="{% url 'contact:contact-list' %}' %}?filter={{ filter }}&orderby={{ orderby }}&page={{ page_obj.next_page_number }}">Next</a>
          </li>
          {% else %}
          <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
          {% endif %}
        </ul>
      </nav>
    </div>
  </div>
</div>

{% endblock content %}

templates/dashboard/contact/show.html
{% extends "dashboard/layouts/base.html" %} {% block title %}Create Tag{%endblock%} 
{% block stylesheets %}{% endblock stylesheets %} {% block content %}

<div class="py-4">
  <nav aria-label="breadcrumb" class="d-none d-md-inline-block">
    <ol class="breadcrumb breadcrumb-dark breadcrumb-transparent">
      <li class="breadcrumb-item">
        <a href="#">
          <svg
            class="icon icon-xxs"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6"
            ></path>
          </svg>
        </a>
      </li>
      <li class="breadcrumb-item"><a href="#">Tables</a></li>
      <li class="breadcrumb-item active" aria-current="page">
        contact show
      </li>
    </ol>
  </nav>
</div>

<div class="card border-0 shadow mb-4">
  <div class="card-body">
      <div class="row mt-4">
        <div class="col-lg-6">
          <label>Subject:</label>
          {{ contact.subject}}
        </div>
        <div class="col-lg-6">
          <label>Email:</label>
          {{ contact.email}}
        </div>
        <div class="col-lg-6">
          <label>Email:</label>
          {{ contact.content}}
        </div>
        <div class="col-lg-6">
          <label>Created:</label>
          {{ contact.created}}
        </div>
      </div>
  </div>
</div>

{% endblock content %} {% block javascripts %}{% endblock javascripts %}