api/urls.py
from django.urls import include, re_path
from rest_framework import routers

from api.views import (APICategoryViewSet, APIPostViewSet, APIProfileViewSet,
                       APISubCategoryViewSet, APITagViewSet, NewsLetterView,
                       UserViewSet)
from blog.models import Post

router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'tags', APITagViewSet)
router.register(r'posts', APIPostViewSet)
router.register(r'categories', APICategoryViewSet)
router.register(r'subcategories', APISubCategoryViewSet)
router.register(r'profile', APIProfileViewSet)



urlpatterns = [
    re_path(r'^', include(router.urls)),
    re_path(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    re_path(r'^newsletter/',NewsLetterView.as_view(), name = "subscribe"),

    # re_path(r'^posts/',APIPostListCreateView.as_view(), name = "list"),
    # re_path(r'^post/(?P<pk>[0-9a-f]{8}-[0-9a-f]{4}-[0-5][0-9a-f]{3}-[089ab][0-9a-f]{3}-[0-9a-f]{12})/$', APIPostDetailView.as_view(), name = 'detail'),
    # re_path(r'^post/(?P<pk>[0-9a-f]{8}-[0-9a-f]{4}-[0-5][0-9a-f]{3}-[089ab][0-9a-f]{3}-[0-9a-f]{12})/edit/$', APIPostUpdateDestroyDetailView.as_view(), name = 'edit'),
    # re_path(r'^tags/', APITagListCreateView.as_view(), name = 'list'),
    # re_path(r'^tag/(?P<pk>[-\d]+)/', APITagDetailView.as_view(), name = 'detail'),
    # re_path(r'^tag/(?P<pk>[-\d]+)/edit/$', APITagEditView.as_view(), name = 'edit'),
    
]

dashboard/urls.py
from django.contrib.sitemaps.views import sitemap
from django.urls import re_path

from dashboard.sitemaps import PostSitemap, StaticViewSitemap

from . import views

sitemaps = {
    'static': StaticViewSitemap,
    'post':PostSitemap
}

app_name = 'dashboard'

urlpatterns = [
    re_path(r'home/',views.DashboardView.as_view(), name = 'home'), 
    re_path(r'^password/$', 
        views.ChangePasswordView.as_view(),name='password_change'),
    
    re_path(r'^list-post/$', views.PostListView.as_view(), name = 'post-list'), 
    re_path(r'^create-post/$', views.PostCreateView.as_view(), name = 'post-create'), 
    re_path(r'^(?P<pk>[0-9a-f]{8}-[0-9a-f]{4}-[0-5][0-9a-f]{3}-[089ab][0-9a-f]{3}-[0-9a-f]{12})/delete-post/$', views.PostDeleteView.as_view(), name = 'post-delete'),
    re_path(r'^(?P<pk>[0-9a-f]{8}-[0-9a-f]{4}-[0-5][0-9a-f]{3}-[089ab][0-9a-f]{3}-[0-9a-f]{12})/edit-post/$', views.PostUpdateView.as_view(), name='post-update'),
    re_path(r'^list-news/$', views.NewListView.as_view(), name = 'new-list'), 
    re_path(r'^create-news/$', views.NewCreateView.as_view(), name = 'new-create'), 
    re_path(r'^(?P<pk>[0-9a-f]{8}-[0-9a-f]{4}-[0-5][0-9a-f]{3}-[089ab][0-9a-f]{3}-[0-9a-f]{12})/delete-new/$', views.NewDeleteView.as_view(), name = 'new-delete'),
    re_path(r'^(?P<pk>[0-9a-f]{8}-[0-9a-f]{4}-[0-5][0-9a-f]{3}-[089ab][0-9a-f]{3}-[0-9a-f]{12})/edit-new/$', views.NewUpdateView.as_view(), name='new-update'),
    re_path(r'^sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),

]

insurance/urls.py

from dj_rest_auth.registration.views import ConfirmEmailView, VerifyEmailView
from dj_rest_auth.views import PasswordResetConfirmView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path, re_path

from insurance import views

urlpatterns = [
    re_path(r'^i18n/', include('django.conf.urls.i18n')),
    re_path(r'^', include('accounts.urls',namespace='accounts')),
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^', include('blog.urls')),
    re_path(r'^new/', include('news.urls')),
    re_path(r'^search/', include('search.urls')),
    re_path(r'^dashboard/', include('dashboard.urls')),
    re_path(r'^tag/', include('tag.urls')),
    re_path(r'^about/', include('aboutus.urls' ,namespace='about_us')),
    re_path(r'^settings/', include('aboutus.urls')),
    re_path(r'^team/', include('team.urls')),
    re_path(r'^category/', include('category.urls')),
    re_path(r'^contact/', include('contact.urls')),
    re_path(r'^faq/', include('faq.urls')),
    re_path(r'^customer-feedback/', include('feedback.urls')),
    re_path(r'^user/', include('users.urls')),
    re_path(r'^frontend/', include('renewal.urls')),
    re_path(r'^ticket/', include('tickets.urls')),
    re_path(r'^social-auth/', include('social_django.urls', namespace='social')),
    re_path(r'^ratings/', include('star_ratings.urls', namespace='ratings')),
    re_path(r'^', include('django.contrib.auth.urls')),
    re_path(r'^__debug__/', include('debug_toolbar.urls')),
    re_path(r'^accounts/login/$', auth_views.LoginView.as_view(template_name='frontend/accounts/login.html'), name='login'),
    re_path(r'^accounts/logout/$', auth_views.LogoutView.as_view(), name='logout'),
    re_path(r'^accounts/reset/$',
        auth_views.PasswordResetView.as_view(
            template_name='frontend/accounts/password_reset.html',
            html_email_template_name='frontend/accounts/password_reset_email.html',
            email_template_name='frontend/accounts/password_reset_email.html',
            subject_template_name='frontend/accounts/password_reset_subject.txt'
        ),
        name='password_reset'),
    re_path(r'^accounts/reset/done/$',
        auth_views.PasswordResetDoneView.as_view(template_name='frontend/accounts/password_reset_done.html'),
        name='password_reset_done'),
    re_path(r'^accounts/reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        auth_views.PasswordResetConfirmView.as_view(template_name='frontend/accounts/password_reset_confirm.html'),
        name='password_reset_confirm'),
    re_path(r'^accounts/reset/complete/$',
        auth_views.PasswordResetCompleteView.as_view(template_name='frontend/accounts/password_reset_complete.html'),
        name='password_reset_complete'),
    re_path(r'^settings/password/done/$',
        auth_views.PasswordChangeDoneView.as_view(template_name='frontend/accounts/password_change_done.html'),
        name='password_change_done'),
    re_path(r'^.*\.*', views.pages, name='pages'),   

    #######################
        ### DRF ###
    ####################### 
    # re_path(r'^api/', include('api.urls')),
    # re_path(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    # re_path(r'^api/v1/rest-auth/', include('dj_rest_auth.urls')),
    # re_path(r'^api/v1/rest-auth/registration/', include('dj_rest_auth.registration.urls')),
    # re_path(r'^api/v1/rest-auth/account-confirm-email/(?P<key>[-:\w]+)/$',  ConfirmEmailView.as_view(), name='account_confirm_email'),
    # re_path(r'^api/v1/rest-auth/account-confirm-email/', VerifyEmailView.as_view(), name='account_email_verification_sent'),
    # re_path(r'^api/v1/rest-auth/password/reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_URL)


users/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path

from . import views

app_name = 'user'

urlpatterns = [

    re_path(r'^create/', views.ProfileView.as_view(), name='user-create'),
    re_path(r'^list/', views.UserListView.as_view(), name = 'user-list'), 
    re_path(r'^(?P<pk>[-\w]+)/delete/', views.DeleteUserView.as_view(), name = 'user-delete'),
    re_path(r'^edit/(?P<pk>[-\d]+)/$', views.ProfileUpdateView.as_view(), name='user-update'),
    re_path(r'^password-change/', views.ChangePasswordView.as_view(), name='password_change'),
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)+static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import (LoginRequiredMixin,
                                        PermissionRequiredMixin)
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models.query_utils import Q
from django.shortcuts import redirect
from django.urls.base import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import ListView, TemplateView
from django.views.generic.edit import CreateView, DeleteView, UpdateView

from blog.forms import PostForm
from blog.models import Post
from news.forms import NewForm
from news.models import New

User = get_user_model()
from django.contrib.auth.views import PasswordChangeView


class DashboardView(LoginRequiredMixin, TemplateView):
    template_name = 'dashboard/dashboard/home.html'

    def get_context_data(self, **kwargs):
        return {'segment':'داشبورد بیمه'}


@method_decorator(csrf_exempt, name='dispatch')
class ChangePasswordView(SuccessMessageMixin, PasswordChangeView):
    template_name='dashboard/accounts/password_change.html'
    success_message = "پسوردتان با موفقیت تغیرر یافت"
    success_url = reverse_lazy('dashboard:password_change')
   


class PostListView(PermissionRequiredMixin,LoginRequiredMixin, ListView):
    model = Post
    context_object_name = 'posts'
    template_name = 'dashboard/blog/list.html'
    paginate_by = 10
    permission_required = "post.view_post"

    def handle_no_permission(self):
        messages.warning(
            self.request, " شما اجازه دسترسی به این صفحه رو ندارید")
        return redirect("dashboard:home")


    # it is for pagination
    def get_queryset(self):
        filter_val = self.request.GET.get("filter", "")
        order_by = self.request.GET.get("orderby", "pk")
        if filter_val != "":
            post = Post.objects.filter(Q(title__contains=filter_val) | Q(
                description__contains=filter_val)).order_by(order_by)
        else:
            post = Post.objects.all().order_by(order_by)
        return post


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["filter"] = self.request.GET.get("filter", "")
        context["orderby"] = self.request.GET.get("orderby", "pk")
        context["all_table_fields"] = Post._meta.get_fields()
        context['segment'] = "لیست پست"
        return context

@method_decorator(csrf_exempt, name='dispatch')
class PostCreateView(SuccessMessageMixin, PermissionRequiredMixin, LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostForm
    context_object_name = "form"
    template_name = "dashboard/blog/create.html"
    success_url = reverse_lazy('dashboard:post-list')
    success_message = "پست با موفقیت ایجاد شد !"
    permission_required = "post.create_post"

    def handle_no_permission(self):
        messages.warning(
            self.request, " شما اجازه دسترسی به این صفحه رو ندارید")
        return redirect("dashboard:home")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["segment"] = "ایجاد پست"
        return context
    
  

@method_decorator(csrf_exempt, name='dispatch')
class PostDeleteView(SuccessMessageMixin, PermissionRequiredMixin, LoginRequiredMixin, DeleteView):
    model = Post
    permission_required = "post.delete_post"
    template_name = 'dashboard/blog/list.html'
    success_url = reverse_lazy('dashboard:post-list')


    def handle_no_permission(self):
        messages.warning(
            self.request, " شما اجازه دسترسی به این صفحه رو ندارید")
        return redirect("dashboard:home")

    def get(self, request, *args, **kwargs):
        pk = kwargs.get("pk")
        if pk is not None:
            post_object = Post.objects.get_queryset().filter(pk=pk)
            if post_object is not None:
                post_object.delete()
                messages.success(request, "پست با موفقیت حذف گردید!")
                return redirect('dashboard:post-list')
        return redirect('dashboard/blog/list.html')


@method_decorator(csrf_exempt, name='dispatch')
class PostUpdateView(SuccessMessageMixin, PermissionRequiredMixin,LoginRequiredMixin, UpdateView):

    form_class = PostForm
    model = Post
    permission_required = "post.update_post"
    pk_url_kwarg = 'pk'
    template_name = 'dashboard/blog/edit.html'
    success_url = reverse_lazy('dashboard:post-list')
    success_message = "پست با موفقیت ویرایش گردید!"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["segment"] = "ویرایش پست"
        return context
    
    def handle_no_permission(self):
        messages.warning(
            self.request, " شما اجازه دسترسی به این صفحه رو ندارید")
        return redirect("dashboard:home")






# =======================================
#  ##############داشبورد###############
# =======================================


class NewListView(PermissionRequiredMixin,LoginRequiredMixin, ListView):
    model = New
    context_object_name = 'news'
    template_name = 'dashboard/news/list.html'
    paginate_by = 10
    permission_required = "new.view_news"

    def handle_no_permission(self):
        messages.warning(
            self.request, " شما اجازه دسترسی به این صفحه رو ندارید")
        return redirect("dashboard:home")

    # it is for pagination
    def get_queryset(self):
        filter_val = self.request.GET.get("filter", "")
        order_by = self.request.GET.get("orderby", "pk")
        if filter_val != "":
            new = New.objects.filter(Q(title__contains=filter_val) | Q(
                description__contains=filter_val)).order_by(order_by)
        else:
            new = New.objects.all().order_by(order_by)
        return new


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["filter"] = self.request.GET.get("filter", "")
        context["orderby"] = self.request.GET.get("orderby", "pk")
        context["all_table_fields"] = New._meta.get_fields()
        context['segment'] = "لیست خبر"
        return context


@method_decorator(csrf_exempt, name='dispatch')
class NewCreateView(SuccessMessageMixin, PermissionRequiredMixin, LoginRequiredMixin, CreateView):
    model = New
    form_class = NewForm
    context_object_name = "form"
    template_name = "dashboard/news/create.html"
    success_url = reverse_lazy('dashboard:new-list')
    success_message = "خبر با موفقیت ایجاد شد !"
    permission_required = "new.create_news"

    def handle_no_permission(self):
        messages.warning(
            self.request, " شما اجازه دسترسی به این صفحه رو ندارید")
        return redirect("dashboard:home")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["segment"] = "ایجاد خبر"
        return context
    
  

@method_decorator(csrf_exempt, name='dispatch')
class NewDeleteView(PermissionRequiredMixin, LoginRequiredMixin, DeleteView):
    model = New
    permission_required = "new.delete_post"
    template_name = 'dashboard/news/list.html'
    success_url = reverse_lazy('dashboard:new-list')


    def handle_no_permission(self):
        messages.warning(
            self.request, " شما اجازه دسترسی به این صفحه رو ندارید")
        return redirect("dashboard:home")

    def get(self, request, *args, **kwargs):
        pk = kwargs.get("pk")
        if pk is not None:
            post_object = New.objects.get_queryset().filter(pk=pk)
            if post_object is not None:
                post_object.delete()
                messages.success(request, "خبر با موفقیت حذف گردید!")
                return redirect('dashboard:new-list')
        return redirect('dashboard/new/list.html')



@method_decorator(csrf_exempt, name='dispatch')
class NewUpdateView(SuccessMessageMixin, PermissionRequiredMixin,LoginRequiredMixin, UpdateView):

    form_class = NewForm
    model = New
    permission_required = "new.update_new"
    pk_url_kwarg = 'pk'
    template_name = 'dashboard/news/edit.html'
    success_url = reverse_lazy('dashboard:new-list')
    success_message = "خبر با موفقیت ویرایش گردید!"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["segment"] = "ویرایش خبر"
        return context
    
    def handle_no_permission(self):
        messages.warning(
            self.request, " شما اجازه دسترسی به این صفحه رو ندارید")
        return redirect("dashboard:home")




templates/dashboard/user/create.html
{% extends "dashboard/layouts/base.html" %}
{% load static %}
{% block content %}
{% if messages %}
{% for message in messages %}
<div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
  <div {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</div>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}
{% endif %}
{% include "dashboard/includes/_headnav.html" %}

<form method="POST" enctype="multipart/form-data" novalidate>
    {% csrf_token %}
    
    <div class="row">
        <div class="col-12 col-xl-8">
            <div class="card card-body bg-white border-light shadow-sm mb-4">
                <h2 class="h5 mb-4">اطلاعات شما</h2>
                <div class="row">
                    <div class="col-md-6 mb-3">
                        <div>
                            <label for="first_name">نام </label>
                            <input name="first_name" class="form-control {% if form.user.errors.first_name %} border-danger
                                    {% endif %}" id="first_name" type="text" name="first_name"
                                placeholder="Enter your first name" value="{{ profile.user.first_name }}">
                            {% for error in form.user.errors.first_name %}
                            <p class="text-danger">{{ error }}</p>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="col-md-6 mb-3">
                        <div>
                            <label for="last_name">نام خانوادگی</label>
                            <input name="last_name" class="form-control {% if form.user.errors.last_name %} border-danger
                                    {% endif %}" id="last_name" type="text" placeholder="Also your last name"
                                value="{{ profile.user.last_name }}">

                            {% for error in form.user.errors.last_name %}
                            <p class="text-danger">{{ error }}</p>
                            {% endfor %}
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-4 mb-3">
                        <div class="form-group">
                            <label for="email">ایمیل</label>
                            <input name="email" class="form-control" id="email" type="email"
                                placeholder="name@company.com" value="{{ profile.user.email }}" readonly>
                        </div>
                    </div>
                    <div class="col-md-4 mb-3">
                        <div class="form-group">
                            <label for="phone">تلفن همراه</label>
                            <input name="mobile" class="form-control {% if form.errors.mobile %} border-danger
                                    {% endif %}" id="phone" type="text" value="{{ profile.user.mobile }}">
                            {% for error in form.errors.phone %}
                            <p class="text-danger">{{ error }}</p>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="col-md-4 mb-3">
                        <div class="form-group">
                            <label for="phone">کدملی</label>
                            <input name="code" class="form-control {% if form.errors.code %} border-danger
                                    {% endif %}" id="code" type="text" value="{{ profile.code }}">
                            {% for error in form.errors.phone %}
                            <p class="text-danger">{{ error }}</p>
                            {% endfor %}
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-12 mb-3">
                        <div class="form-group">
                            <label for="address">آدرس</label>
                            <input name="address" class="form-control" id="address" type="text" placeholder="آدرس "
                                value="{{ profile.address|default:'' }}">
                        </div>
                    </div>

                </div>
                <div class="row">
                    <div class="col-sm-4 mb-3">
                        <div class="form-group">
                            <label for="number">تلفن ثابت</label>
                            <input name="phone" class="form-control" id="phone" type="text" placeholder="شماره تلفن."
                                value="{{ profile.phone|default:'' }}">
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group">
                            <label for="zip">کدپستی</label>
                            <input name="zip" class="form-control" id="zip" type="tel" placeholder="کدپستی"
                                value="{{ profile.zip|default:'' }}">
                        </div>
                        {% for error in form.errors.code %}
                        <p class="text-danger">{{ error }}</p>
                        {% endfor %}
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group">
                            <label for="file">تصویر</label>
                            <input name="avatar" class="form-control" id="file" type="file"
                                value="{{ profile.get_avatar|default:'' }}">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <button type="submit" class="btn btn-primary btn-block mt-5">ویرایش پروفایل</button>
                </div>
            </div>
        </div>
        <div class="col-12 col-xl-4">
            <div class="row">
                <div class="col-12 mb-4">
                    <div class="card border-light text-center p-0">
                        <div class="profile-cover rounded-top"
                            data-background="{% static 'assets/backend/img/profile-cover.jpg' %}"></div>
                        <div class="card-body pb-5">
                            <img src="{{ user.profile.get_avatar }}" class="avatar-xl rounded-circle mx-auto mt-n7 mb-4"
                                alt="Neil Portrait">
                            <h4 class="h3">نام: {{ profile.user.first_name }}</h4>
                            <h4 class="font-weight-normal">نام خانوادگی: {{ profile.user.last_name }}</h4>
                            <h5 class="font-weight-normal">
                                ایمیل: {{ request.user.email }}
                            </h5>
                            <p class="text-gray mb-4">آدرس: {{ profile.address|default:'' }}</p>
                            <a class="btn btn-sm btn-secondary" href="#">فرستادن پیام</a>
                        </div>
                    </div>
                </div>
           
            </div>
        </div>
    </div>
</form>




{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

templates/dashboard/user/list.html
{% extends "dashboard/layouts/base.html" %}
 {% block content %}
{% if messages %}
{% for message in messages %}
<div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
  <div {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</div>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}
{% endif %}
{% include "dashboard/includes/_headnav.html" %}
<div class="card border-0 shadow mb-4">
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-centered table-nowrap mb-0 rounded">
        <thead class="thead-light">
          <tr>
            <th class="border-0 rounded-start">#</th>
            <th class="border-0">تصویر</th>
            <th class="border-0">نام</th>
            <th class="border-0">نام خانوادگی</th>
            <th class="border-0">موبایل</th>
            <th class="border-0">تاریخ تولد</th>
            <th class="border-0">وضعیت</th>
            <th class="border-0">تاریخ انتشار</th>
            <th class="border-0">حذف / ویرایش</th>
          </tr>
        </thead>
        <tbody>
          {% if user.is_superuser == True %}
          {% for user in users %}
          <tr>
            <td><a href="#" class="text-primary fw-bold">{{ user.pk}}</a></td>
            <td>{% if user.profile.avatar %} <img src="{{ user.profile.get_avatar }}" class="avatar rounded-circle"
                alt="Image placeholder" />{% else %}
              <img src="../../static/assets/backend/img/team/profile-picture-1.jpg" class="avatar rounded-circle"
                width=70 />
              {% endif %}
            </td>
     
            <td>{{ user.first_name}}</td>
            <td>{{ user.last_name}}</td>
            <td>{{ user.profile.phone}}</td>
            <td>{{ user.profile.birthday}}</td>

            <td>{% if user.is_superuser == True %} سوپر آدمین {% elif user.is_staff == True and user.is_superuser == False %} کارمند{% else %}کاربر{% endif %}</td>
            <td class="text-success">
              <div class="d-flex align-items-center">
                <svg class="icon icon-xs me-1" fill="currentColor" viewBox="0 0 20 20"
                  xmlns="http://www.w3.org/2000/svg">
                  <path fill-rule="evenodd"
                    d="M14.707 12.707a1 1 0 01-1.414 0L10 9.414l-3.293 3.293a1 1 0 01-1.414-1.414l4-4a1 1 0 011.414 0l4 4a1 1 0 010 1.414z"
                    clip-rule="evenodd"></path>
                </svg>
                <span class="fw-bold">{{ user.profile.published }}</span>
              </div>
            </td>
            <td>
              <form method="POST" action="{% url 'user:user-list' %}">
                {% csrf_token %}
                <a href="{% url 'user:user-delete' user.pk %}"><img src="https://img.icons8.com/external-flatart-icons-solid-flatarticons/30/F25081/external-trash-office-flatart-icons-solid-flatarticons.png"/></a>
              </form>
            </td>
          </tr>
          {% endfor %}
          {% endif %}
        </tbody>
      </table>
    </div>
  </div>
  <div class="card-body">
    <nav aria-label="Page navigation example">
      <ul class="pagination">
        {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link"
            href="{% url 'user:user-list' %}' %}?filter={{ filter }}&orderby={{ orderby }}&page={{ page_obj.previous_page_number }}">Previous</a>
        </li>
        {% else %}
        <li class="page-item disabled"><a class="page-link" href="#">قبلی</a></li>
        {% endif %}
        {% for i in paginator.page_range %}
        <li class="page-item {% if i == page_obj.number %}active{% endif %}"><a class="page-link"
            href="{% url 'user:user-list' %}' %}?filter={{ filter }}&orderby={{ orderby }}&page={{ i }}">{{ i }}</a></li>
        {% endfor %}
        {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link"
            href="{% url 'user:user-list' %}' %}?filter={{ filter }}&orderby={{ orderby }}&page={{ page_obj.next_page_number }}">Next</a>
        </li>
        {% else %}
        <li class="page-item disabled"><a class="page-link" href="#">بعدی</a></li>
        {% endif %}
  </div>
</div>

{% endblock content %}